import unittest
from learn_unittest.test_math_function import TestMathFunction
from learn_unittest.HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()
    # suite.addTest(TestMathFunction('test_add'))
    # suite.addTest(TestMathFunction('test_minus'))
    tests = [TestMathFunction('test_add'), TestMathFunction('test_minus'), TestMathFunction('test_multi'),
             TestMathFunction('test_divide')]
    suite.addTests(tests)

    with open('HTMLReport.html', 'wb+') as file:
        runner = HTMLTestRunner(stream=file,
                                title='Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)

    # runner = unittest.TextTestRunner()
    # runner.run(suite)
